name: app
description: "QuickSlot — sports slot booking app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # state management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8

  # navigation
  go_router: ^17.0.0

  # networking
  dio: ^5.9.0
  talker_dio_logger: ^5.1.1
  connectivity_plus: ^7.0.0

  # DI
  get_it: ^9.1.1

  # UI
  flutter_screenutil: ^5.9.3

  # utilities
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
